#pragma once
#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdarg.h>

#ifndef EXTERNC
#ifndef __cplusplus
#define EXTERNC
#else
#define EXTERNC extern "C"
#endif
#endif

#ifndef __FILE_NAME__
#define __FILE_NAME__ __FILE__
#endif
#ifndef __FILENAME__
#define __FILENAME__ __FILE_NAME__
#endif

////////////////////////////////////////////////////////////////////////////
EXTERNC void dbgOutput(unsigned chl, const void* data, int size);
EXTERNC void dbgString(unsigned chl, const char* str);
EXTERNC void dbgPrintf(const char* fmt, ...);
EXTERNC void dbgPrintfc(unsigned chl, const char* fmt, ...);
EXTERNC void dbgPrintfp(unsigned chl, const char* fmt, va_list* ap);
EXTERNC void dbgPrintfs(const char* name, unsigned chl, const char* fmt, ...);
EXTERNC void dbgPrintfx(const char* name, unsigned chl, const char* fmt, va_list* ap);
EXTERNC void dbgDump(unsigned chl, const void* data, int size);
EXTERNC void dbgDumpFile(unsigned chl, const char* url);
EXTERNC const char* dbgPath(const char* path);
EXTERNC const char* dbgFunc(const char* func);
////////////////////////////////////////////////////////////////////////////
EXTERNC void __dbgPrintfs(const char* name, unsigned chl, ...);
EXTERNC void __dbgPrintfx(const char* name, unsigned chl, va_list* ap);
EXTERNC void dbgErrProcess(const char* file, unsigned line, unsigned error);
#define dbgErrProc(e) dbgErrProcess(__FILENAME__,__LINE__,e);
////////////////////////////////////////////////////////////////////////////
#define dbgChnEntry(x,...) __dbgPrintfs(#x,dbg_chn_##x,__FILENAME__, __LINE__,__FUNCTION__,##__VA_ARGS__)
////////////////////////////////////////////////////////////////////////////
#define dbg_chn_err 0x0
#define dbg_chn_warn 0x1
#define dbg_chn_cmd 0x2
#define dbg_chn_note 0x3
#define dbg_chn_info 0x4
#define dbg_chn_dev 0x5
#define dbg_chn_ext 0x6
#define dbg_chn_test 0x7
#define dbg_chn_api 0x8
#define dbg_chn_mem 0x9
#define dbg_chn_a 0xa//dynlibs error
#define dbg_chn_b 0xb//dynlibs info
#define dbg_chn_c 0xc//dynlibs test
#define dbg_chn_msg 0xd
#define dbg_chn_script 0xe
#define dbg_chn_io 0xf
#define dbg_chn_10 0x10//msvc
#define dbg_chn_11 0x11//ssvc
#define dbg_chn_12 0x12//mmgr
#define dbg_chn_13 0x13//nx
#define dbg_chn_14 0x14
#define dbg_chn_15 0x15
#define dbg_chn_16 0x16
#define dbg_chn_17 0x17
#define dbg_chn_18 0x18
#define dbg_chn_19 0x19
#define dbg_chn_1a 0x1a
#define dbg_chn_1b 0x1b
#define dbg_chn_1c 0x1c
#define dbg_chn_1d 0x1d
#define dbg_chn_1e 0x1e
#define dbg_chn_1f 0x1f
#define dbg_chn_max 0x20
#define dbg_chn_map_default 0xffff0cfful
////////////////////////////////////////////////////////////////////////////
#define dbg_err_printf(...)				dbgChnEntry(err,##__VA_ARGS__)
#define dbg_warn_printf(...)			dbgChnEntry(warn,##__VA_ARGS__)
#define dbg_cmd_printf(...)				dbgChnEntry(cmd,##__VA_ARGS__)
#define dbg_note_printf(...)			dbgChnEntry(note,##__VA_ARGS__)
#define dbg_info_printf(...)			dbgChnEntry(info,##__VA_ARGS__)
#define dbg_dev_printf(...)				dbgChnEntry(dev,##__VA_ARGS__)
#define dbg_api_printf(...)				dbgChnEntry(api,##__VA_ARGS__)
#define dbg_test_printf(...)			dbgChnEntry(test,##__VA_ARGS__)
#define dbg_mem_printf(...)				dbgChnEntry(mem,##__VA_ARGS__)
#define dbg_msg_printf(...)				dbgChnEntry(msg,##__VA_ARGS__)
#define dbg_a_printf(...)				dbgChnEntry(a,##__VA_ARGS__)
#define dbg_b_printf(...)				dbgChnEntry(b,##__VA_ARGS__)
#define dbg_c_printf(...)				dbgChnEntry(c,##__VA_ARGS__)
#define dbg_ext_printf(...)				dbgChnEntry(ext,##__VA_ARGS__)
#define dbg_script_printf(...)			dbgChnEntry(script,##__VA_ARGS__)
#define dbg_io_printf(...)				dbgChnEntry(io,##__VA_ARGS__)
////////////////////////////////////////////////////////////////////////////
#define returnIf(v,c) if(c)return v
#define returnIfE(v,c,e) if(c){dbgErrProc(e);return v;}
////////////////////////////////////////////////////////////////////////////
enum {
	DBG_OUTPUT_END = 1 << 8,
	DBG_OUTPUT_CHN = 1 << 9,
	DBG_OUTPUT_DUMP = 1 << 10,
	DBG_OUTPUT_SKIP = 1 << 11,
	DBG_OUTPUT_POS = 1 << 12,
	DBG_OUTPUT_KEYS = 1 << 13,
	DBG_OUTPUT_OUTPUT = 1 << 14,
};
////////////////////////////////////////////////////////////////////////////
#define dbgChn(x,...)					dbg_##x##_printf(0,##__VA_ARGS__)
#define dbgChnL(x,...)					dbg_##x##_printf(DBG_OUTPUT_END,##__VA_ARGS__)
#define dbgChnX(x,...)					dbg_##x##_printf(DBG_OUTPUT_CHN,##__VA_ARGS__)
#define dbgChnXL(x,...)					dbg_##x##_printf(DBG_OUTPUT_CHN|DBG_OUTPUT_END,##__VA_ARGS__)
#define dbgChnP(x,...)					dbg_##x##_printf(DBG_OUTPUT_CHN|DBG_OUTPUT_POS,##__VA_ARGS__)
#define dbgChnPL(x)						dbg_##x##_printf(DBG_OUTPUT_CHN|DBG_OUTPUT_POS|DBG_OUTPUT_END,0)
#define dbgChnPXL(x,...)				dbg_##x##_printf(DBG_OUTPUT_CHN|DBG_OUTPUT_POS|DBG_OUTPUT_END,##__VA_ARGS__)
#define dbgChnPCL(x,c,...)				dbg_##x##_printf(DBG_OUTPUT_CHN|DBG_OUTPUT_POS|DBG_OUTPUT_END|(c?0:DBG_OUTPUT_SKIP),##__VA_ARGS__)
#define dbgChnDump(x,d,z)				dbg_##x##_printf(DBG_OUTPUT_CHN|DBG_OUTPUT_DUMP,d,z,0)
#define dbgChnDumpL(x,d,z,l)			dbg_##x##_printf(DBG_OUTPUT_CHN|DBG_OUTPUT_DUMP,d,z,l)
#define dbgChnOutput(x,d,z)				dbg_##x##_printf(DBG_OUTPUT_CHN|DBG_OUTPUT_OUTPUT,d,z)
#define dbgChnOutputL(x,d,z)			dbg_##x##_printf(DBG_OUTPUT_CHN|DBG_OUTPUT_OUTPUT|DBG_OUTPUT_END,d,z)
#define dbgChnOutputPL(x,d,z)			dbg_##x##_printf(DBG_OUTPUT_CHN|DBG_OUTPUT_OUTPUT|DBG_OUTPUT_POS|DBG_OUTPUT_END,d,z)
#define dbgChnSL(x,v)					dbgChn(x,#v"=%s\n",((const char*)v))
#define dbgChnDL(x,v)					dbgChn(x,#v"=%d\n",((int)v))
#define dbgChnPDL(x,v)					dbgChnPXL(x,#v"=%d",((int)v))
#define dbgChnPDLZ(x,v)					dbgChnPCL(x,v,#v"=%d",((int)v))
#define dbgChnPPL(x,v)					dbgChnPXL(x,#v"=%p",((void*)v))
#define dbgChnPPLZ(x,v)					dbgChnPCL(x,v,#v"=%p",((void*)v))
#define dbgChnPSL(x,v)					dbgChnPXL(x,#v"=%s",(v?((const char*)v):""))
#define dbgChnPSLZ(x,v)					dbgChnPCL(x,v,#v"=%s",v)
#define dbgChnPSL0(x,v)					dbgChnPXL(x,#v"=%s",(const char*)v)
#define dbgChnPQL(x,v)					dbgChnPXL(x,#v"=0x%08x%08x",((uint32_t*)&v)[1],((uint32_t*)&v)[0])
#define dbgChnPUL(x,v)					dbgChnPXL(x,#v"=%u",((uint32_t)v))
#define dbgChnPFL(x,v)					dbgChnPXL(x,#v"=%f",((float)v))
#define dbgChnPHL(x,v)					dbgChnPXL(x,#v"=%08x",((uint32_t)v))
#define dbgChnString(x,s)				dbgString(dbg_chn_##x,s)
#define dbgChnPEL(x,e,...)				dbgErrProc(e);dbgChnPXL(x,##__VA_ARGS__)
#define dbgChnIf(x,c)					if(c){dbgChnPXL(x,#c);}
#define dbgChnIfS(x,c,s,...)			if(c){dbgChnPXL(x,#c"#"#s,##__VA_ARGS__);}
#define dbgChnIfE(x,c,e)				if(c){dbgChnPEL(x,e,#c"[%d]",e);}
#define dbgChnIfES(x,c,e,s,...)			if(c){dbgChnPEL(x,e,#c"[%d]""#"#s,e,##__VA_ARGS__);}
#define returnIfChnC(x,v,c)				if(c){dbgChnPXL(x,#c);return v;}
#define returnIfChnCS(x,v,c,s,...)		if(c){dbgChnPXL(x,#c"#"#s,##__VA_ARGS__);return v;}
#define returnIfChnC0(x,c)				if(c){dbgChnPXL(x,#c);return;}
#define returnIfChnCS0(x,c,s,...)		if(c){dbgChnPXL(x,#c"#"#s,##__VA_ARGS__);return;}
#define returnIfChnF(x,v,c,f)			if(c){dbgChnPXL(x,#c);f;return v;}
#define returnIfChnFS(x,v,c,f,s,...)	if(c){dbgChnPXL(x,#c"#"#s,##__VA_ARGS__);f;return v;}
#define returnIfChnE(x,v,c,e)			if(c){dbgChnPEL(x,e,#c"[%d]",e);return v;}
#define returnIfChnES(x,v,c,e,s,...)	if(c){dbgChnPEL(x,e,#c"[%d]""#"#s,e,##__VA_ARGS__);return v;}
#define returnIfChnE0(x,c,e)			if(c){dbgChnPEL(x,e,#c"[%d]",e);return;}
#define returnIfChnES0(x,c,e,s,...)		if(c){dbgChnPEL(x,e,#c"[%d]""#"#s,e,##__VA_ARGS__);return;}
#define returnIfChnEF(x,v,c,e,f)		if(c){dbgChnPEL(x,e,#c"[%d]",e);f;return v;}
#define returnIfChnEFS(x,v,c,e,f,s,...)	if(c){dbgChnPEL(x,e,#c"[%d]""#"#s,e,##__VA_ARGS__);f;return v;}
////////////////////////////////////////////////////////////////////////////
#define dbgErr(...)							dbgErrProc(1);dbgChn(err,##__VA_ARGS__)
#define dbgErrX(...)						dbgErrProc(1);dbgChnX(err,##__VA_ARGS__)
#define dbgErrP(...)						dbgErrProc(1);dbgChnP(err,##__VA_ARGS__)
#define dbgErrDL(v)							dbgErrProc(1);dbgChnDL(err,v)
#define dbgErrSL(v)							dbgErrProc(1);dbgChnSL(err,v)
#define dbgErrPL()							dbgErrProc(1);dbgChnPL(err)
#define dbgErrPXL(s,...)					dbgErrProc(1);dbgChnPXL(err,s,##__VA_ARGS__)
#define dbgErrPDL(v)						dbgErrProc(1);dbgChnPDL(err,v)
#define dbgErrPPL(v)						dbgErrProc(1);dbgChnPPL(err,v)
#define dbgErrPQL(v)						dbgErrProc(1);dbgChnPQL(err,v)
#define dbgErrPSL(v)						dbgErrProc(1);dbgChnPSL(err,v)
#define dbgErrPUL(v)						dbgErrProc(1);dbgChnPUL(err,v)
#define dbgErrPHL(v)						dbgErrProc(1);dbgChnPHL(err,v)
#define dbgErrPSL0(v)						dbgErrProc(1);dbgChnPSL0(err,v)
#define dbgErrDump(d,z)						dbgErrProc(1);dbgChnDump(err,d,z)
#define dbgErrOutput(d,z)					dbgErrProc(1);dbgChnOutput(err,d,z)
#define dbgErrOutputL(d,z)					dbgErrProc(1);dbgChnOutputL(err,d,z)
#define dbgErrString(s)						dbgErrProc(1);dbgChnString(err,s)
#define dbgErrPEL(e,...)					dbgChnPEL(err,e,##__VA_ARGS__)
#define dbgErrIf(c)							dbgChnIfE(err,c,1)
#define dbgErrIfS(c,s,...)					dbgChnIfES(err,c,1,s,##__VA_ARGS__)	
#define dbgErrIfE(c,e)						dbgChnIfE(err,c,e)				
#define dbgErrIfES(c,e,s,...)				dbgChnIfES(err,c,e,s,##__VA_ARGS__)	
#define returnIfErrC(v,c)					returnIfChnE(err,v,c,1)			
#define returnIfErrCS(v,c,s,...)			returnIfChnES(err,v,c,1,s,##__VA_ARGS__)	
#define returnIfErrC0(c)					returnIfChnE0(err,c,1)			
#define returnIfErrCS0(c,s,...)				returnIfChnES0(err,c,1,s,##__VA_ARGS__)	
#define returnIfErrF(v,c,f)					returnIfChnEF(err,v,c,1,f)		
#define returnIfErrFS(v,c,f,s,...)			returnIfChnEFS(err,v,c,1,f,s,##__VA_ARGS__)	
#define returnIfErrE(v,c,e)					returnIfChnE(err,v,c,e)			
#define returnIfErrES(v,c,e,s,...)			returnIfChnES(err,v,c,e,s,##__VA_ARGS__)		
#define returnIfErrE0(c,e)					returnIfChnE0(err,c,e)				
#define returnIfErrES0(c,e,s,...)			returnIfChnES0(err,c,e,s,##__VA_ARGS__)		
#define returnIfErrEF(v,c,e,f)				returnIfChnEF(err,v,c,e,f)			
#define returnIfErrEFS(v,c,e,f,s,...)		returnIfChnEFS(err,v,c,e,f,s,##__VA_ARGS__)
////////////////////////////////////////////////////////////////////////////
#define dbgWarn(...)						dbgChn(warn,##__VA_ARGS__)
#define dbgWarnX(...)						dbgChnX(warn,##__VA_ARGS__)
#define dbgWarnP(...)						dbgChnP(warn,##__VA_ARGS__)
#define dbgWarnXL(...)						dbgChnXL(warn,##__VA_ARGS__)
#define dbgWarnDL(v)						dbgChnDL(warn,v)
#define dbgWarnSL(v)						dbgChnSL(warn,v)
#define dbgWarnPL()							dbgChnPL(warn)
#define dbgWarnPXL(s,...)					dbgChnPXL(warn,s,##__VA_ARGS__)
#define dbgWarnPDL(v)						dbgChnPDL(warn,v)
#define dbgWarnPPL(v)						dbgChnPPL(warn,v)
#define dbgWarnPQL(v)						dbgChnPQL(warn,v)
#define dbgWarnPSL(v)						dbgChnPSL(warn,v)
#define dbgWarnPDLZ(v)						dbgChnPDLZ(warn,v)
#define dbgWarnPPLZ(v)						dbgChnPPLZ(warn,v)
#define dbgWarnPSLZ(v)						dbgChnPSLZ(warn,v)
#define dbgWarnPSL0(v)						dbgChnPSL0(warn,v)
#define dbgWarnPEL(e,...)					dbgChnPEL(warn,e,##__VA_ARGS__)
#define dbgWarnDump(d,z)					dbgChnDump(warn,d,z)
#define dbgWarnDumpL(d,z,l)					dbgChnDumpL(warn,d,z,l)
#define dbgWarnString(s)					dbgChnString(warn,s)
#define dbgWarnIf(c)						dbgChnIf(warn,c)
#define dbgWarnIfS(c,s,...)					dbgChnIfS(warn,c,s,##__VA_ARGS__)
#define returnIfWarnC(v,c)					returnIfChnC(warn,v,c)			
#define returnIfWarnCS(v,c,s,...)			returnIfChnCS(warn,v,c,s,##__VA_ARGS__)	
#define returnIfWarnC0(c)					returnIfChnC0(warn,c)			
#define returnIfWarnCS0(c,s,...)			returnIfChnCS0(warn,c,s,##__VA_ARGS__)	
#define returnIfWarnF(v,c,f)				returnIfChnF(warn,v,c,f)		
#define returnIfWarnFS(v,c,f,s,...)			returnIfChnFS(warn,v,c,f,s,##__VA_ARGS__)	
#define returnIfWarnE(v,c,e)				returnIfChnE(warn,v,c,e)			
#define returnIfWarnES(v,c,e,s,...)			returnIfChnES(warn,v,c,e,s,##__VA_ARGS__)		
#define returnIfWarnE0(c,e)					returnIfChnE0(warn,c,e)				
#define returnIfWarnES0(c,e,s,...)			returnIfChnES0(warn,c,e,s,##__VA_ARGS__)		
#define returnIfWarnEF(v,c,e,f)				returnIfChnEF(warn,v,c,e,f)			
#define returnIfWarnEFS(v,c,e,f,s,...)		returnIfChnEFS(warn,v,c,e,f,s,##__VA_ARGS__)
////////////////////////////////////////////////////////////////////////////
#define dbgCmd(...)							dbgChn(cmd,##__VA_ARGS__)
#define dbgCmdX(...)						dbgChnX(cmd,##__VA_ARGS__)
#define dbgCmdP(...)						dbgChnP(cmd,##__VA_ARGS__)
#define dbgCmdXL(...)						dbgChnXL(cmd,##__VA_ARGS__)
#define dbgCmdDL(v)							dbgChnDL(cmd,v)
#define dbgCmdSL(v)							dbgChnSL(cmd,v)
#define dbgCmdPL()							dbgChnPL(cmd)
#define dbgCmdPXL(s,...)					dbgChnPXL(cmd,s,##__VA_ARGS__)
#define dbgCmdPDL(v)						dbgChnPDL(cmd,v)
#define dbgCmdPPL(v)						dbgChnPPL(cmd,v)
#define dbgCmdPQL(v)						dbgChnPQL(cmd,v)
#define dbgCmdPSL(v)						dbgChnPSL(cmd,v)
#define dbgCmdPDLZ(v)						dbgChnPDLZ(cmd,v)
#define dbgCmdPPLZ(v)						dbgChnPPLZ(cmd,v)
#define dbgCmdPSLZ(v)						dbgChnPSLZ(cmd,v)
#define dbgCmdPSL0(v)						dbgChnPSL0(cmd,v)
#define dbgCmdPEL(e,...)					dbgChnPEL(cmd,e,##__VA_ARGS__)
#define dbgCmdDump(d,z)						dbgChnDump(cmd,d,z)
#define dbgCmdString(s)						dbgChnString(cmd,s)
#define dbgCmdIf(c)							dbgChnIf(cmd,c)
#define dbgCmdIfS(c,s,...)					dbgChnIfS(cmd,c,s,##__VA_ARGS__)
#define returnIfCmdC(v,c)					returnIfChnC(cmd,v,c)
#define returnIfCmdCS(v,c,s,...)			returnIfChnCS(cmd,v,c,s,##__VA_ARGS__)
#define returnIfCmdC0(c)					returnIfChnC0(cmd,c)
#define returnIfCmdCS0(c,s,...)				returnIfChnCS0(cmd,c,s,##__VA_ARGS__)
#define returnIfCmdF(v,c,f)					returnIfChnF(cmd,v,c,f)
#define returnIfCmdFS(v,c,f,s,...)			returnIfChnFS(cmd,v,c,f,s,##__VA_ARGS__)
#define returnIfCmdE(v,c,e)					returnIfChnE(cmd,v,c,e)
#define returnIfCmdES(v,c,e,s,...)			returnIfChnES(cmd,v,c,e,s,##__VA_ARGS__)
#define returnIfCmdE0(c,e)					returnIfChnE0(cmd,c,e)
#define returnIfCmdES0(c,e,s,...)			returnIfChnES0(cmd,c,e,s,##__VA_ARGS__)
#define returnIfCmdEF(v,c,e,f)				returnIfChnEF(cmd,v,c,e,f)
#define returnIfCmdEFS(v,c,e,f,s,...)		returnIfChnEFS(cmd,v,c,e,f,s,##__VA_ARGS__)

////////////////////////////////////////////////////////////////////////////
#define dbgNote(...)						dbgChn(note,##__VA_ARGS__)
#define dbgNoteX(...)						dbgChnX(note,##__VA_ARGS__)
#define dbgNoteP(...)						dbgChnP(note,##__VA_ARGS__)
#define dbgNoteDL(v)						dbgChnDL(note,v)
#define dbgNoteSL(v)						dbgChnSL(note,v)
#define dbgNotePL()							dbgChnPL(note)
#define dbgNotePXL(s,...)					dbgChnPXL(note,s,##__VA_ARGS__)
#define dbgNotePDL(v)						dbgChnPDL(note,v)
#define dbgNotePPL(v)						dbgChnPPL(note,v)
#define dbgNotePQL(v)						dbgChnPQL(note,v)
#define dbgNotePSL(v)						dbgChnPSL(note,v)
#define dbgNotePUL(v)						dbgChnPUL(note,v)
#define dbgNotePHL(v)						dbgChnPHL(note,v)
#define dbgNotePDLZ(v)						dbgChnPDLZ(note,v)
#define dbgNotePPLZ(v)						dbgChnPPLZ(note,v)
#define dbgNotePSLZ(v)						dbgChnPSLZ(note,v)
#define dbgNotePSL0(v)						dbgChnPSL0(note,v)
#define dbgNotePEL(e,...)					dbgChnPEL(note,e,##__VA_ARGS__)
#define dbgNoteDump(d,z)					dbgChnDump(note,d,z)
#define dbgNoteOutput(d,z)					dbgChnOutput(note,d,z)
#define dbgNoteOutputL(d,z)					dbgChnOutputL(note,d,z)
#define dbgNoteString(s)					dbgChnString(note,s)
#define dbgNoteIf(c)						dbgChnIf(note,c)
#define dbgNoteIfS(c,s,...)					dbgChnIfS(note,c,s,##__VA_ARGS__)
#define returnIfNoteC(v,c)					returnIfChnC(note,v,c)			
#define returnIfNoteCS(v,c,s,...)			returnIfChnCS(note,v,c,s,##__VA_ARGS__)	
#define returnIfNoteC0(c)					returnIfChnC0(note,c)			
#define returnIfNoteCS0(c,s,...)			returnIfChnCS0(note,c,s,##__VA_ARGS__)	
#define returnIfNoteF(v,c,f)				returnIfChnF(note,v,c,f)		
#define returnIfNoteFS(v,c,f,s,...)			returnIfChnFS(note,v,c,f,s,##__VA_ARGS__)	
#define returnIfNoteE(v,c,e)				returnIfChnE(note,v,c,e)			
#define returnIfNoteES(v,c,e,s,...)			returnIfChnES(note,v,c,e,s,##__VA_ARGS__)		
#define returnIfNoteE0(c,e)					returnIfChnE0(note,c,e)				
#define returnIfNoteES0(c,e,s,...)			returnIfChnES0(note,c,e,s,##__VA_ARGS__)		
#define returnIfNoteEF(v,c,e,f)				returnIfChnEF(note,v,c,e,f)			
#define returnIfNoteEFS(v,c,e,f,s,...)		returnIfChnEFS(note,v,c,e,f,s,##__VA_ARGS__)

////////////////////////////////////////////////////////////////////////////
#define dbgInfo(...)						dbgChn(info,##__VA_ARGS__)
#define dbgInfoX(...)						dbgChnX(info,##__VA_ARGS__)
#define dbgInfoP(...)						dbgChnP(info,##__VA_ARGS__)
#define dbgInfoDL(v)						dbgChnDL(info,v)
#define dbgInfoSL(v)						dbgChnSL(info,v)
#define dbgInfoPL()							dbgChnPL(info)
#define dbgInfoPXL(s,...)					dbgChnPXL(info,s,##__VA_ARGS__)
#define dbgInfoPDL(v)						dbgChnPDL(info,v)
#define dbgInfoPPL(v)						dbgChnPPL(info,v)
#define dbgInfoPQL(v)						dbgChnPQL(info,v)
#define dbgInfoPSL(v)						dbgChnPSL(info,v)
#define dbgInfoPUL(v)						dbgChnPUL(info,v)
#define dbgInfoPHL(v)						dbgChnPHL(info,v)
#define dbgInfoPSL0(v)						dbgChnPSL0(info,v)
#define dbgInfoPDLZ(v)						dbgChnPDLZ(info,v)
#define dbgInfoPPLZ(v)						dbgChnPPLZ(info,v)
#define dbgInfoPSLZ(v)						dbgChnPSLZ(info,v)
#define dbgInfoPEL(e,...)					dbgChnPEL(info,e,##__VA_ARGS__)
#define dbgInfoDump(d,z)					dbgChnDump(info,d,z)
#define dbgInfoOutput(d,z)					dbgChnOutput(info,d,z)
#define dbgInfoOutputL(d,z)					dbgChnOutputL(info,d,z)
#define dbgInfoString(s)					dbgChnString(info,s)
#define dbgInfoIf(c)						dbgChnIf(info,c)
#define dbgInfoIfS(c,s,...)					dbgChnIfS(info,c,s,##__VA_ARGS__)	
#define returnIfInfoC(v,c)					returnIfChnC(info,v,c)			
#define returnIfInfoCS(v,c,s,...)			returnIfChnCS(info,v,c,s,##__VA_ARGS__)	
#define returnIfInfoC0(c)					returnIfChnC0(info,c)			
#define returnIfInfoCS0(c,s,...)			returnIfChnCS0(info,c,s,##__VA_ARGS__)	
#define returnIfInfoF(v,c,f)				returnIfChnF(info,v,c,f)		
#define returnIfInfoFS(v,c,f,s,...)			returnIfChnFS(info,v,c,f,s,##__VA_ARGS__)	
#define returnIfInfoE(v,c,e)				returnIfChnE(info,v,c,e)			
#define returnIfInfoES(v,c,e,s,...)			returnIfChnES(info,v,c,e,s,##__VA_ARGS__)		
#define returnIfInfoE0(c,e)					returnIfChnE0(info,c,e)				
#define returnIfInfoES0(c,e,s,...)			returnIfChnES0(info,c,e,s,##__VA_ARGS__)		
#define returnIfInfoEF(v,c,e,f)				returnIfChnEF(info,v,c,e,f)			
#define returnIfInfoEFS(v,c,e,f,s,...)		returnIfChnEFS(info,v,c,e,f,s,##__VA_ARGS__)
////////////////////////////////////////////////////////////////////////////
#define dbgDev(...)							dbgChn(dev,##__VA_ARGS__)
#define dbgDevX(...)						dbgChnX(dev,##__VA_ARGS__)
#define dbgDevP(...)						dbgChnP(dev,##__VA_ARGS__)
#define dbgDevDL(v)							dbgChnDL(dev,v)
#define dbgDevSL(v)							dbgChnSL(dev,v)
#define dbgDevPL()							dbgChnPL(dev)
#define dbgDevPXL(s,...)					dbgChnPXL(dev,s,##__VA_ARGS__)
#define dbgDevPDL(v)						dbgChnPDL(dev,v)
#define dbgDevPPL(v)						dbgChnPPL(dev,v)
#define dbgDevPQL(v)						dbgChnPQL(dev,v)
#define dbgDevPSL(v)						dbgChnPSL(dev,v)
#define dbgDevPDLZ(v)						dbgChnPDLZ(dev,v)
#define dbgDevPPLZ(v)						dbgChnPPLZ(dev,v)
#define dbgDevPSLZ(v)						dbgChnPSLZ(dev,v)
#define dbgDevPSL0(v)						dbgChnPSL0(dev,v)
#define dbgDevPEL(e,...)					dbgChnPEL(dev,e,##__VA_ARGS__)
#define dbgDevDump(d,z)						dbgChnDump(dev,d,z)
#define dbgDevString(s)						dbgChnString(dev,s)
#define dbgDevIf(c)							dbgChnIf(dev,c)
#define dbgDevIfS(c,s,...)					dbgChnIfS(dev,c,s,##__VA_ARGS__)
#define returnIfDevC(v,c)					returnIfChnC(dev,v,c)			
#define returnIfDevCS(v,c,s,...)			returnIfChnCS(dev,v,c,s,##__VA_ARGS__)	
#define returnIfDevC0(c)					returnIfChnC0(dev,c)			
#define returnIfDevCS0(c,s,...)				returnIfChnCS0(dev,c,s,##__VA_ARGS__)	
#define returnIfDevF(v,c,f)					returnIfChnF(dev,v,c,f)		
#define returnIfDevFS(v,c,f,s,...)			returnIfChnFS(dev,v,c,f,s,##__VA_ARGS__)	
#define returnIfDevE(v,c,e)					returnIfChnE(dev,v,c,e)			
#define returnIfDevES(v,c,e,s,...)			returnIfChnES(dev,v,c,e,s,##__VA_ARGS__)		
#define returnIfDevE0(c,e)					returnIfChnE0(dev,c,e)				
#define returnIfDevES0(c,e,s,...)			returnIfChnES0(dev,c,e,s,##__VA_ARGS__)		
#define returnIfDevEF(v,c,e,f)				returnIfChnEF(dev,v,c,e,f)			
#define returnIfDevEFS(v,c,e,f,s,...)		returnIfChnEFS(dev,v,c,e,f,s,##__VA_ARGS__)
////////////////////////////////////////////////////////////////////////////
#define dbgTest(...)						dbgChn(test,##__VA_ARGS__)
#define dbgTestL(...)						dbgChnL(test,##__VA_ARGS__)
#define dbgTestX(...)						dbgChnX(test,##__VA_ARGS__)
#define dbgTestXL(...)						dbgChnXL(test,##__VA_ARGS__)
#define dbgTestP(...)						dbgChnP(test,##__VA_ARGS__)
#define dbgTestDL(v)						dbgChnDL(test,v)
#define dbgTestSL(v)						dbgChnSL(test,v)
#define dbgTestPL()							dbgChnPL(test)
#define dbgTestPXL(s,...)					dbgChnPXL(test,s,##__VA_ARGS__)
#define dbgTestPDL(v)						dbgChnPDL(test,v)
#define dbgTestPPL(v)						dbgChnPPL(test,v)
#define dbgTestPQL(v)						dbgChnPQL(test,v)
#define dbgTestPSL(v)						dbgChnPSL(test,v)
#define dbgTestPUL(v)						dbgChnPUL(test,v)
#define dbgTestPHL(v)						dbgChnPHL(test,v)
#define dbgTestPFL(v)						dbgChnPFL(test,v)
#define dbgTestPDLZ(v)						dbgChnPDLZ(test,v)
#define dbgTestPPLZ(v)						dbgChnPPLZ(test,v)
#define dbgTestPSLZ(v)						dbgChnPSLZ(test,v)
#define dbgTestPSL0(v)						dbgChnPSL0(test,v)
#define dbgTestPEL(e,...)					dbgChnPEL(test,e,##__VA_ARGS__)
#define dbgTestDump(d,z)					dbgChnDump(test,d,z)
#define dbgTestDumpL(d,z,l)					dbgChnDumpL(test,d,z,l)
#define dbgTestOutput(d,z)					dbgChnOutput(test,d,z)
#define dbgTestOutputL(d,z)					dbgChnOutputL(test,d,z)
#define dbgTestString(s)					dbgChnString(test,s)
#define dbgTestIf(c)						dbgChnIf(test,c)
#define dbgTestIfS(c,s,...)					dbgChnIfS(test,c,s,##__VA_ARGS__)
#define returnIfTestC(v,c)					returnIfChnC(test,v,c)			
#define returnIfTestCS(v,c,s,...)			returnIfChnCS(test,v,c,s,##__VA_ARGS__)	
#define returnIfTestC0(c)					returnIfChnC0(test,c)			
#define returnIfTestCS0(c,s,...)			returnIfChnCS0(test,c,s,##__VA_ARGS__)	
#define returnIfTestF(v,c,f)				returnIfChnF(test,v,c,f)		
#define returnIfTestFS(v,c,f,s,...)			returnIfChnFS(test,v,c,f,s,##__VA_ARGS__)	
#define returnIfTestE(v,c,e)				returnIfChnE(test,v,c,e)			
#define returnIfTestES(v,c,e,s,...)			returnIfChnES(test,v,c,e,s,##__VA_ARGS__)		
#define returnIfTestE0(c,e)					returnIfChnE0(test,c,e)				
#define returnIfTestES0(c,e,s,...)			returnIfChnES0(test,c,e,s,##__VA_ARGS__)		
#define returnIfTestEF(v,c,e,f)				returnIfChnEF(test,v,c,e,f)			
#define returnIfTestEFS(v,c,e,f,s,...)		returnIfChnEFS(test,v,c,e,f,s,##__VA_ARGS__)
////////////////////////////////////////////////////////////////////////////
#define dbgApi(...)							dbgChn(api,##__VA_ARGS__)
#define dbgApiX(...)						dbgChnX(api,##__VA_ARGS__)
#define dbgApiP(...)						dbgChnP(api,##__VA_ARGS__)
#define dbgApiDL(v)							dbgChnDL(api,v)
#define dbgApiSL(v)							dbgChnSL(api,v)
#define dbgApiPL()							dbgChnPL(api)
#define dbgApiPXL(s,...)					dbgChnPXL(api,s,##__VA_ARGS__)
#define dbgApiPDL(v)						dbgChnPDL(api,v)
#define dbgApiPPL(v)						dbgChnPPL(api,v)
#define dbgApiPQL(v)						dbgChnPQL(api,v)
#define dbgApiPSL(v)						dbgChnPSL(api,v)
#define dbgApiPDLZ(v)						dbgChnPDLZ(api,v)
#define dbgApiPPLZ(v)						dbgChnPPLZ(api,v)
#define dbgApiPSLZ(v)						dbgChnPSLZ(api,v)
#define dbgApiPSL0(v)						dbgChnPSL0(api,v)
#define dbgApiPEL(e,...)					dbgChnPEL(api,e,##__VA_ARGS__)
#define dbgApiDump(d,z)						dbgChnDump(api,d,z)
#define dbgApiString(s)						dbgChnString(api,s)
#define dbgApiIf(c)							dbgChnIf(api,c)
#define dbgApiIfS(c,s,...)					dbgChnIfS(api,c,s,##__VA_ARGS__)
#define returnIfApiC(v,c)					returnIfChnC(api,v,c)			
#define returnIfApiCS(v,c,s,...)			returnIfChnCS(api,v,c,s,##__VA_ARGS__)	
#define returnIfApiC0(c)					returnIfChnC0(api,c)			
#define returnIfApiCS0(c,s,...)				returnIfChnCS0(api,c,s,##__VA_ARGS__)	
#define returnIfApiF(v,c,f)					returnIfChnF(api,v,c,f)		
#define returnIfApiFS(v,c,f,s,...)			returnIfChnFS(api,v,c,f,s,##__VA_ARGS__)	
#define returnIfApiE(v,c,e)					returnIfChnE(api,v,c,e)			
#define returnIfApiES(v,c,e,s,...)			returnIfChnES(api,v,c,e,s,##__VA_ARGS__)		
#define returnIfApiE0(c,e)					returnIfChnE0(api,c,e)				
#define returnIfApiES0(c,e,s,...)			returnIfChnES0(api,c,e,s,##__VA_ARGS__)		
#define returnIfApiEF(v,c,e,f)				returnIfChnEF(api,v,c,e,f)			
#define returnIfApiEFS(v,c,e,f,s,...)		returnIfChnEFS(api,v,c,e,f,s,##__VA_ARGS__)
////////////////////////////////////////////////////////////////////////////
#define dbgMedia(...)						dbgChn(media,##__VA_ARGS__)
#define dbgMediaL(...)						dbgChnL(media,##__VA_ARGS__)
#define dbgMediaX(...)						dbgChnX(media,##__VA_ARGS__)
#define dbgMediaP(...)						dbgChnP(media,##__VA_ARGS__)
#define dbgMediaDL(v)						dbgChnDL(media,v)
#define dbgMediaSL(v)						dbgChnSL(media,v)
#define dbgMediaPL()						dbgChnPL(media)
#define dbgMediaPXL(s,...)					dbgChnPXL(media,s,##__VA_ARGS__)
#define dbgMediaPDL(v)						dbgChnPDL(media,v)
#define dbgMediaPPL(v)						dbgChnPPL(media,v)
#define dbgMediaPQL(v)						dbgChnPQL(media,v)
#define dbgMediaPSL(v)						dbgChnPSL(media,v)
#define dbgMediaPUL(v)						dbgChnPUL(media,v)
#define dbgMediaPHL(v)						dbgChnPHL(media,v)
#define dbgMediaPFL(v)						dbgChnPFL(media,v)
#define dbgMediaPDLZ(v)						dbgChnPDLZ(media,v)
#define dbgMediaPPLZ(v)						dbgChnPPLZ(media,v)
#define dbgMediaPSLZ(v)						dbgChnPSLZ(media,v)
#define dbgMediaPSL0(v)						dbgChnPSL0(media,v)
#define dbgMediaPEL(e,...)					dbgChnPEL(media,e,##__VA_ARGS__)
#define dbgMediaDump(d,z)					dbgChnDump(media,d,z)
#define dbgMediaDumpL(d,z,l)				dbgChnDumpL(media,d,z,l)
#define dbgMediaOutput(d,z)					dbgChnOutput(media,d,z)
#define dbgMediaOutputL(d,z)				dbgChnOutputL(media,d,z)
#define dbgMediaString(s)					dbgChnString(media,s)
#define dbgMediaIf(c)						dbgChnIf(media,c)
#define dbgMediaIfS(c,s,...)				dbgChnIfS(media,c,s,##__VA_ARGS__)
#define returnIfMediaC(v,c)					returnIfChnC(media,v,c)			
#define returnIfMediaCS(v,c,s,...)			returnIfChnCS(media,v,c,s,##__VA_ARGS__)	
#define returnIfMediaC0(c)					returnIfChnC0(media,c)			
#define returnIfMediaCS0(c,s,...)			returnIfChnCS0(media,c,s,##__VA_ARGS__)	
#define returnIfMediaF(v,c,f)				returnIfChnF(media,v,c,f)		
#define returnIfMediaFS(v,c,f,s,...)		returnIfChnFS(media,v,c,f,s,##__VA_ARGS__)	
#define returnIfMediaE(v,c,e)				returnIfChnE(media,v,c,e)			
#define returnIfMediaES(v,c,e,s,...)		returnIfChnES(media,v,c,e,s,##__VA_ARGS__)		
#define returnIfMediaE0(c,e)				returnIfChnE0(media,c,e)				
#define returnIfMediaES0(c,e,s,...)			returnIfChnES0(media,c,e,s,##__VA_ARGS__)		
#define returnIfMediaEF(v,c,e,f)			returnIfChnEF(media,v,c,e,f)			
#define returnIfMediaEFS(v,c,e,f,s,...)		returnIfChnEFS(media,v,c,e,f,s,##__VA_ARGS__)
////////////////////////////////////////////////////////////////////////////
#define dbgIO(...)							dbgChn(io,##__VA_ARGS__)
#define dbgIOL(...)							dbgChnL(io,##__VA_ARGS__)
#define dbgIOX(...)							dbgChnX(io,##__VA_ARGS__)
#define dbgIOP(...)							dbgChnP(io,##__VA_ARGS__)
#define dbgIODL(v)							dbgChnDL(io,v)
#define dbgIOSL(v)							dbgChnSL(io,v)
#define dbgIOPL()							dbgChnPL(io)
#define dbgIOPXL(s,...)						dbgChnPXL(io,s,##__VA_ARGS__)
#define dbgIOPDL(v)							dbgChnPDL(io,v)
#define dbgIOPPL(v)							dbgChnPPL(io,v)
#define dbgIOPQL(v)							dbgChnPQL(io,v)
#define dbgIOPSL(v)							dbgChnPSL(io,v)
#define dbgIOPUL(v)							dbgChnPUL(io,v)
#define dbgIOPHL(v)							dbgChnPHL(io,v)
#define dbgIOPFL(v)							dbgChnPFL(io,v)
#define dbgIOPDLZ(v)						dbgChnPDLZ(io,v)
#define dbgIOPPLZ(v)						dbgChnPPLZ(io,v)
#define dbgIOPSLZ(v)						dbgChnPSLZ(io,v)
#define dbgIOPSL0(v)						dbgChnPSL0(io,v)
#define dbgIOPEL(e,...)						dbgChnPEL(io,e,##__VA_ARGS__)
#define dbgIODump(d,z)						dbgChnDump(io,d,z)
#define dbgIODumpL(d,z,l)					dbgChnDumpL(io,d,z,l)
#define dbgIOOutput(d,z)					dbgChnOutput(io,d,z)
#define dbgIOOutputL(d,z)					dbgChnOutputL(io,d,z)
#define dbgIOString(s)						dbgChnString(io,s)
#define dbgIOIf(c)							dbgChnIf(io,c)
#define dbgIOIfS(c,s,...)					dbgChnIfS(io,c,s,##__VA_ARGS__)
#define returnIfIOC(v,c)					returnIfChnC(io,v,c)			
#define returnIfIOCS(v,c,s,...)				returnIfChnCS(io,v,c,s,##__VA_ARGS__)	
#define returnIfIOC0(c)						returnIfChnC0(io,c)			
#define returnIfIOCS0(c,s,...)				returnIfChnCS0(io,c,s,##__VA_ARGS__)	
#define returnIfIOF(v,c,f)					returnIfChnF(io,v,c,f)		
#define returnIfIOFS(v,c,f,s,...)			returnIfChnFS(io,v,c,f,s,##__VA_ARGS__)	
#define returnIfIOE(v,c,e)					returnIfChnE(io,v,c,e)			
#define returnIfIOES(v,c,e,s,...)			returnIfChnES(io,v,c,e,s,##__VA_ARGS__)		
#define returnIfIOE0(c,e)					returnIfChnE0(io,c,e)				
#define returnIfIOES0(c,e,s,...)			returnIfChnES0(io,c,e,s,##__VA_ARGS__)		
#define returnIfIOEF(v,c,e,f)				returnIfChnEF(io,v,c,e,f)			
#define returnIfIOEFS(v,c,e,f,s,...)		returnIfChnEFS(io,v,c,e,f,s,##__VA_ARGS__)
////////////////////////////////////////////////////////////////////////////
#define dbgScript(...)						dbgChn(script,##__VA_ARGS__)
#define dbgScriptL(...)						dbgChnL(script,##__VA_ARGS__)
#define dbgScriptX(...)						dbgChnX(script,##__VA_ARGS__)
#define dbgScriptP(...)						dbgChnP(script,##__VA_ARGS__)
#define dbgScriptDL(v)						dbgChnDL(script,v)
#define dbgScriptSL(v)						dbgChnSL(script,v)
#define dbgScriptPL()						dbgChnPL(script)
#define dbgScriptPXL(s,...)					dbgChnPXL(script,s,##__VA_ARGS__)
#define dbgScriptPDL(v)						dbgChnPDL(script,v)
#define dbgScriptPPL(v)						dbgChnPPL(script,v)
#define dbgScriptPQL(v)						dbgChnPQL(script,v)
#define dbgScriptPSL(v)						dbgChnPSL(script,v)
#define dbgScriptPUL(v)						dbgChnPUL(script,v)
#define dbgScriptPHL(v)						dbgChnPHL(script,v)
#define dbgScriptPFL(v)						dbgChnPFL(script,v)
#define dbgScriptPDLZ(v)					dbgChnPDLZ(script,v)
#define dbgScriptPPLZ(v)					dbgChnPPLZ(script,v)
#define dbgScriptPSLZ(v)					dbgChnPSLZ(script,v)
#define dbgScriptPSL0(v)					dbgChnPSL0(script,v)
#define dbgScriptPEL(e,...)					dbgChnPEL(script,e,##__VA_ARGS__)
#define dbgScriptDump(d,z)					dbgChnDump(script,d,z)
#define dbgScriptDumpL(d,z,l)				dbgChnDumpL(script,d,z,l)
#define dbgScriptOutput(d,z)				dbgChnOutput(script,d,z)
#define dbgScriptOutputL(d,z)				dbgChnOutputL(script,d,z)
#define dbgScriptString(s)					dbgChnString(script,s)
#define dbgScriptIf(c)						dbgChnIf(script,c)
#define dbgScriptIfS(c,s,...)				dbgChnIfS(script,c,s,##__VA_ARGS__)
#define returnIfScriptC(v,c)				returnIfChnC(script,v,c)			
#define returnIfScriptCS(v,c,s,...)			returnIfChnCS(script,v,c,s,##__VA_ARGS__)	
#define returnIfScriptC0(c)					returnIfChnC0(script,c)			
#define returnIfScriptCS0(c,s,...)			returnIfChnCS0(script,c,s,##__VA_ARGS__)	
#define returnIfScriptF(v,c,f)				returnIfChnF(script,v,c,f)		
#define returnIfScriptFS(v,c,f,s,...)		returnIfChnFS(script,v,c,f,s,##__VA_ARGS__)	
#define returnIfScriptE(v,c,e)				returnIfChnE(script,v,c,e)			
#define returnIfScriptES(v,c,e,s,...)		returnIfChnES(script,v,c,e,s,##__VA_ARGS__)		
#define returnIfScriptE0(c,e)				returnIfChnE0(script,c,e)				
#define returnIfScriptES0(c,e,s,...)		returnIfChnES0(script,c,e,s,##__VA_ARGS__)		
#define returnIfScriptEF(v,c,e,f)			returnIfChnEF(script,v,c,e,f)			
#define returnIfScriptEFS(v,c,e,f,s,...)	returnIfChnEFS(script,v,c,e,f,s,##__VA_ARGS__)
////////////////////////////////////////////////////////////////////////////
#define dbgMsg(...)							dbgChn(msg,##__VA_ARGS__)
#define dbgMsgX(...)						dbgChnX(msg,##__VA_ARGS__)
#define dbgMsgP(...)						dbgChnP(msg,##__VA_ARGS__)
#define dbgMsgDL(v)							dbgChnDL(msg,v)
#define dbgMsgSL(v)							dbgChnSL(msg,v)
#define dbgMsgPL()							dbgChnPL(msg)
#define dbgMsgPXL(s,...)					dbgChnPXL(msg,s,##__VA_ARGS__)
#define dbgMsgPDL(v)						dbgChnPDL(msg,v)
#define dbgMsgPPL(v)						dbgChnPPL(msg,v)
#define dbgMsgPQL(v)						dbgChnPQL(msg,v)
#define dbgMsgPSL(v)						dbgChnPSL(msg,v)
#define dbgMsgPUL(v)						dbgChnPUL(msg,v)
#define dbgMsgPHL(v)						dbgChnPHL(msg,v)
#define dbgMsgPDLZ(v)						dbgChnPDLZ(msg,v)
#define dbgMsgPPLZ(v)						dbgChnPPLZ(msg,v)
#define dbgMsgPSLZ(v)						dbgChnPSLZ(msg,v)
#define dbgMsgPSL0(v)						dbgChnPSL0(msg,v)
#define dbgMsgPEL(e,...)					dbgChnPEL(msg,e,##__VA_ARGS__)
#define dbgMsgDump(d,z)						dbgChnDump(msg,d,z)
#define dbgMsgDumpL(d,z,l)					dbgChnDumpL(msg,d,z,l)
#define dbgMsgOutput(d,z)					dbgChnOutput(msg,d,z)
#define dbgMsgOutputL(d,z)					dbgChnOutputL(msg,d,z)
#define dbgMsgString(s)						dbgChnString(msg,s)
#define dbgMsgIf(c)							dbgChnIf(msg,c)
#define dbgMsgIfS(c,s,...)					dbgChnIfS(msg,c,s,##__VA_ARGS__)
#define returnIfMsgC(v,c)					returnIfChnC(msg,v,c)			
#define returnIfMsgCS(v,c,s,...)			returnIfChnCS(msg,v,c,s,##__VA_ARGS__)	
#define returnIfMsgC0(c)					returnIfChnC0(msg,c)			
#define returnIfMsgCS0(c,s,...)				returnIfChnCS0(msg,c,s,##__VA_ARGS__)	
#define returnIfMsgF(v,c,f)					returnIfChnF(msg,v,c,f)		
#define returnIfMsgFS(v,c,f,s,...)			returnIfChnFS(msg,v,c,f,s,##__VA_ARGS__)	
#define returnIfMsgE(v,c,e)					returnIfChnE(msg,v,c,e)			
#define returnIfMsgES(v,c,e,s,...)			returnIfChnES(msg,v,c,e,s,##__VA_ARGS__)		
#define returnIfMsgE0(c,e)					returnIfChnE0(msg,c,e)				
#define returnIfMsgES0(c,e,s,...)			returnIfChnES0(msg,c,e,s,##__VA_ARGS__)		
#define returnIfMsgEF(v,c,e,f)				returnIfChnEF(msg,v,c,e,f)			
#define returnIfMsgEFS(v,c,e,f,s,...)		returnIfChnEFS(msg,v,c,e,f,s,##__VA_ARGS__)
////////////////////////////////////////////////////////////////////////////
#define dbgMem(...)							dbgChn(mem,##__VA_ARGS__)
#define dbgMemX(...)						dbgChnX(mem,##__VA_ARGS__)
#define dbgMemP(...)						dbgChnP(mem,##__VA_ARGS__)
#define dbgMemDL(v)							dbgChnDL(mem,v)
#define dbgMemSL(v)							dbgChnSL(mem,v)
#define dbgMemPL()							dbgChnPL(mem)
#define dbgMemPXL(s,...)					dbgChnPXL(mem,s,##__VA_ARGS__)
#define dbgMemPDL(v)						dbgChnPDL(mem,v)
#define dbgMemPPL(v)						dbgChnPPL(mem,v)
#define dbgMemPQL(v)						dbgChnPQL(mem,v)
#define dbgMemPSL(v)						dbgChnPSL(mem,v)
#define dbgMemPDLZ(v)						dbgChnPDLZ(mem,v)
#define dbgMemPPLZ(v)						dbgChnPPLZ(mem,v)
#define dbgMemPSLZ(v)						dbgChnPSLZ(mem,v)
#define dbgMemPSL0(v)						dbgChnPSL0(mem,v)
#define dbgMemPEL(e,...)					dbgChnPEL(mem,e,##__VA_ARGS__)
#define dbgMemDump(d,z)						dbgChnDump(mem,d,z)
#define dbgMemString(s)						dbgChnString(mem,s)
#define dbgMemIf(c)							dbgChnIf(mem,c)
#define dbgMemIfS(c,s,...)					dbgChnIfS(mem,c,s,##__VA_ARGS__)
#define returnIfMemC(v,c)					returnIfChnC(mem,v,c)			
#define returnIfMemCS(v,c,s,...)			returnIfChnCS(mem,v,c,s,##__VA_ARGS__)	
#define returnIfMemC0(c)					returnIfChnC0(mem,c)			
#define returnIfMemCS0(c,s,...)				returnIfChnCS0(mem,c,s,##__VA_ARGS__)	
#define returnIfMemF(v,c,f)					returnIfChnF(mem,v,c,f)		
#define returnIfMemFS(v,c,f,s,...)			returnIfChnFS(mem,v,c,f,s,##__VA_ARGS__)	
#define returnIfMemE(v,c,e)					returnIfChnE(mem,v,c,e)			
#define returnIfMemES(v,c,e,s,...)			returnIfChnES(mem,v,c,e,s,##__VA_ARGS__)		
#define returnIfMemE0(c,e)					returnIfChnE0(mem,c,e)				
#define returnIfMemES0(c,e,s,...)			returnIfChnES0(mem,c,e,s,##__VA_ARGS__)		
#define returnIfMemEF(v,c,e,f)				returnIfChnEF(mem,v,c,e,f)			
#define returnIfMemEFS(v,c,e,f,s,...)		returnIfChnEFS(mem,v,c,e,f,s,##__VA_ARGS__)
////////////////////////////////////////////////////////////////////////////