CUR_DIR := $(dir $(lastword $(MAKEFILE_LIST)))

COMPILE_SRCS := \
    base/ \
#     container/ \
#     dbg/ \
#     io/ \
#     misc/ \
#     msg/ \

COMPILE_FLAGS += \
    -I$(CUR_DIR)base \
    -I$(CUR_DIR)container \
    -I$(CUR_DIR)dbg \
    -I$(CUR_DIR)io \
    -I$(CUR_DIR)misc \
    -I$(CUR_DIR)msg \
    -I$(CUR_DIR)pligin \
    -I$(CUR_DIR)pool \
    -I$(CUR_DIR)script \
    -I$(CUR_DIR)shm \
    -I$(CUR_DIR)src \
    -I$(CUR_DIR)std \

