CUR_DIR := $(dir $(lastword $(MAKEFILE_LIST)))

COMPILE_SRCS := \
    core/ \
#     container/ \
#     dbg/ \
#     io/ \
#     misc/ \
#     msg/ \

COMPILE_FLAGS += \
    -I$(CUR_DIR)priv
